#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : evolution
Version  : 3.46.0
Release  : 82
URL      : https://download.gnome.org/sources/evolution/3.46/evolution-3.46.0.tar.xz
Source0  : https://download.gnome.org/sources/evolution/3.46/evolution-3.46.0.tar.xz
Summary  : libraries needed for Evolution shell components
Group    : Development/Tools
License  : CC-BY-SA-3.0 GFDL-1.3 LGPL-2.1 LGPL-3.0 OLDAP-2.8
Requires: webkitgtk
BuildRequires : buildreq-cmake
BuildRequires : buildreq-gnome
BuildRequires : glib-dev
BuildRequires : gtk3-dev
BuildRequires : intltool
BuildRequires : itstool
BuildRequires : libgdata-dev
BuildRequires : nspr-dev
BuildRequires : nss-dev
BuildRequires : openldap-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(cairo-gobject)
BuildRequires : pkgconfig(camel-1.2)
BuildRequires : pkgconfig(cryptui-0.0)
BuildRequires : pkgconfig(enchant-2)
BuildRequires : pkgconfig(gail-3.0)
BuildRequires : pkgconfig(gcr-3)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gnome-autoar-0)
BuildRequires : pkgconfig(gnome-desktop-3.0)
BuildRequires : pkgconfig(gsettings-desktop-schemas)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtkspell3-3.0)
BuildRequires : pkgconfig(libcanberra-gtk3)
BuildRequires : pkgconfig(libebackend-1.2)
BuildRequires : pkgconfig(libebook-1.2)
BuildRequires : pkgconfig(libedataserver-1.2)
BuildRequires : pkgconfig(libedataserverui-1.2)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libsoup-3.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(nspr)
BuildRequires : pkgconfig(shared-mime-info)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(webkit2gtk-4.0)
BuildRequires : pkgconfig(webkit2gtk-4.1)
BuildRequires : psmisc

%description
This directory contains files related to Flatpak build of Evolution. Apart
of Evolution itself, it builds also evolution-data-server, and uses it,
the same as evolution-ews for Exchange Web Services accounts.

%prep
%setup -q -n evolution-3.46.0
cd %{_builddir}/evolution-3.46.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663949487
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
%cmake .. -DWITH_NSPR_INCLUDES=/usr/include/ \
-DENABLE_YTNEF=OFF \
-DENABLE_TEXT_HIGHLIGHT=OFF \
-DENABLE_PST_IMPORT=OFF \
-DWITH_NSS_INCLUDES=/usr/include/ \
-DWITH_NSS_INCLUDES=/usr/include/nss3 \
-DENABLE_WEATHER=OFF
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1663949487
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/evolution
cp %{_builddir}/evolution-%{version}/COPYING %{buildroot}/usr/share/package-licenses/evolution/62066b13a35774834f104c2ff075ce679a0f75a3 || :
cp %{_builddir}/evolution-%{version}/COPYING-DOCS.CCBYSA %{buildroot}/usr/share/package-licenses/evolution/981f80d8daa1dc8bff466b65c9b6bfbb3723ccaa || :
cp %{_builddir}/evolution-%{version}/COPYING-DOCS.GFDL %{buildroot}/usr/share/package-licenses/evolution/240c69f006fcb369389272cf0475392633f3b92c || :
cp %{_builddir}/evolution-%{version}/COPYING.LGPL2 %{buildroot}/usr/share/package-licenses/evolution/14c1f9f1263a82d58615c51369e1443c3d9f15bf || :
cp %{_builddir}/evolution-%{version}/COPYING.LGPL3 %{buildroot}/usr/share/package-licenses/evolution/c2e8ebe3551b42d4a868922ec922a8af6452c48b || :
cp %{_builddir}/evolution-%{version}/COPYING.OPENLDAP %{buildroot}/usr/share/package-licenses/evolution/bc06cbdf781c87d2df2fe385214f936d010dd2a2 || :
cp %{_builddir}/evolution-%{version}/docs/COPYING-DOCS.CCBYSA %{buildroot}/usr/share/package-licenses/evolution/981f80d8daa1dc8bff466b65c9b6bfbb3723ccaa || :
cp %{_builddir}/evolution-%{version}/docs/COPYING-DOCS.GFDL %{buildroot}/usr/share/package-licenses/evolution/240c69f006fcb369389272cf0475392633f3b92c || :
cp %{_builddir}/evolution-%{version}/help/COPYING-DOCS.CCBYSA %{buildroot}/usr/share/package-licenses/evolution/981f80d8daa1dc8bff466b65c9b6bfbb3723ccaa || :
cp %{_builddir}/evolution-%{version}/help/COPYING-DOCS.GFDL %{buildroot}/usr/share/package-licenses/evolution/240c69f006fcb369389272cf0475392633f3b92c || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
